const timelineElements = [
  {
    id: 1,
    title: "Web Development Intern",
    companyOrSchool: "Train the Future UG",
    location: "Berlin, Germany",
    description: "First Web Development experience. ",
    buttonText: "Details",
    date: "August 2024 - Pres",
    icon: "work",
    color: "blue",
    tech: ["JavaScript", "HTML", "CSS", "Java"],
  },
  {
    id: 2,
    title: "Full Stack Web Development",
    companyOrSchool: "DCI GmbH",
    location: "Berlin, Germany",
    description: "Having cultivated an interested during COVID-19, I finally embarked on a journey where the mission was to learn and understand the principles of WebDev so that I could have a solid base to enter the industry.",
    buttonText: "Details",
    date: "August 2023 - August 2024",
    icon: "school",
    color: "blue",
    tech: ["JavaScript", "HTML", "CSS", "Java"],
  },
  {
    id: 3,
    title: "Supply Chain Manager",
    companyOrSchool: "Grover SE",
    location: "Berlin, Germany",
    description: "After having worked a few years in the same company, I could finally get a managerial position where I was give lots of responsibilities as well as freedom to make decisions and lead a team.",
    buttonText: "Details",
    date: "October 2020 - June 2023",
    icon: "work",
    color: "purple",
    tech: ["JavaScript", "React", "Node.js", "SQL"],
  },
  {
    id: 4,
    title: "Intern & Jr. Operations Manager",
    companyOrSchool: "Grover SE",
    location: "Berlin, Germany",
    description: "First professional experience in Germany. Started out as an Operations Intern and worked my way up to Juniort Operations Manager 1+ years later.",
    buttonText: "Details",
    date: "April 2018 - October 2020",
    icon: "work",
    color: "yellow",
    tech: ["React", "HTML", "CSS", "JavaScript", "Angular"],
  },
  {
    id: 5,
    title: " Int. Business Admin (Exchange)",
    companyOrSchool: "Europa Universität Viadrina",
    location: "Frankfurt (Oder), Germany",
    description: "Exchange semester in Germany. Awarded the ISAP Scholarship granted by the German Academic Exchance Service (DAAD).",
    buttonText: "Details",
    date: "October 2017 - March 2018",
    icon: "school",
    color: "yellow",
    tech: ["React", "HTML", "CSS", "JavaScript", "Angular"],
  },
  {
    id: 6,
    title: "BIB",
    companyOrSchool: "Pontificia Univerisdad Javeriana",
    location: "Cali, Colombia",
    description: "Bachelor of International Business.",
    buttonText: "Details",
    date: "June 2014 - November 2018",
    icon: "school",
    color: "yellow",
    tech: ["React", "HTML", "CSS", "JavaScript", "Angular"],
  },
];

export default timelineElements;
