const timelineElements = [
  {
    id: 1,
    title: "Web Development Intern",
    companyOrSchool: "Train the Future UG",
    location: "Berlin, Germany",
    description: "Completed my degree in Computer Science",
    buttonText: "Details",
    date: "08.2024 - Present",
    icon: "work",
    color: "blue",
    tech: ["JavaScript", "HTML", "CSS", "Java"],
  },
  {
    id: 2,
    title: "Full Stack Web Development",
    companyOrSchool: "DCI GmbH",
    location: "Berlin, Germany",
    description: "Completed my degree in Computer Science",
    buttonText: "Details",
    date: "2014-2018",
    icon: "school",
    color: "blue",
    tech: ["JavaScript", "HTML", "CSS", "Java"],
  },
  {
    id: 3,
    title: "Supply Chain Manager",
    companyOrSchool: "Grover SE",
    location: "Berlin, Germany",
    description: "Worked on web development projects",
    buttonText: "Details",
    date: "2020-2023",
    icon: "work",
    color: "purple",
    tech: ["JavaScript", "React", "Node.js", "SQL"],
  },
  {
    id: 4,
    title: "Intern & Jr. Operations Manager",
    companyOrSchool: "Grover SE",
    location: "Berlin, Germany",
    description: "Joined a tech company as a front-end developer",
    buttonText: "Details",
    date: "2018-2020",
    icon: "work",
    color: "yellow",
    tech: ["React", "HTML", "CSS", "JavaScript", "Angular"],
  },
  {
    id: 5,
    title: " Int. Business Admin (Exchange)",
    companyOrSchool: "Europa Universität Viadrina",
    location: "Frankfurt (Oder), Berlin",
    description: "Joined a tech company as a front-end developer",
    buttonText: "Details",
    date: "2017-2018",
    icon: "school",
    color: "yellow",
    tech: ["React", "HTML", "CSS", "JavaScript", "Angular"],
  },
  {
    id: 6,
    title: "BIB",
    companyOrSchool: "Pontificia Univerisdad Javeriana",
    location: "Cali, Colombia",
    description: "Joined a tech company as a front-end developer",
    buttonText: "Details",
    date: "2014-2018",
    icon: "school",
    color: "yellow",
    tech: ["React", "HTML", "CSS", "JavaScript", "Angular"],
  },
];

export default timelineElements;
